// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVLC_E00UOp5QGL22PvioevUViIOBnUU',
    appId: '1:688730428333:web:7fd87ea9da139604460724',
    messagingSenderId: '688730428333',
    projectId: 'agrefiege-9e11a',
    authDomain: 'agrefiege-9e11a.firebaseapp.com',
    storageBucket: 'agrefiege-9e11a.appspot.com',
    measurementId: 'G-6G8XC5PMVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTRvwHwh3LVBiSnIJ6mZi8tg8brigcFw',
    appId: '1:688730428333:android:1ade68149ab52118460724',
    messagingSenderId: '688730428333',
    projectId: 'agrefiege-9e11a',
    storageBucket: 'agrefiege-9e11a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDgFMgEg_h-nVz2rUWmwzhUz4mgVGHT_E',
    appId: '1:688730428333:ios:c35b4310d3f248d3460724',
    messagingSenderId: '688730428333',
    projectId: 'agrefiege-9e11a',
    storageBucket: 'agrefiege-9e11a.appspot.com',
    iosBundleId: 'com.faris.agrefiege.agrefiege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDgFMgEg_h-nVz2rUWmwzhUz4mgVGHT_E',
    appId: '1:688730428333:ios:c35b4310d3f248d3460724',
    messagingSenderId: '688730428333',
    projectId: 'agrefiege-9e11a',
    storageBucket: 'agrefiege-9e11a.appspot.com',
    iosBundleId: 'com.faris.agrefiege.agrefiege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVLC_E00UOp5QGL22PvioevUViIOBnUU',
    appId: '1:688730428333:web:04e17fb3ac17dbde460724',
    messagingSenderId: '688730428333',
    projectId: 'agrefiege-9e11a',
    authDomain: 'agrefiege-9e11a.firebaseapp.com',
    storageBucket: 'agrefiege-9e11a.appspot.com',
    measurementId: 'G-FZ5TGS5TEE',
  );
}
